pipeline {
    agent {
        node('docker') {
        stage('Build') {
            docker.image('python:3.10.1-alpine').inside {
                sh 'python --version'
                }
            }
        }
    }

    stages {
        stage('hello-world'){
            steps{
                sh 'cd jenkins-example && python hello-world.py'
            }
        }
        stage('Test'){
            steps{
                sh 'cd jenkins-example && python sum_test.py'
            }
        }
    }

    post{
        failure{
            echo 'The pipeline failed.'
        }
    }

}