pipeline {
    agent any

    stages {
        stage('hello-world'){
            steps{
                script {
                    sh 'cd jenkins-example && ls'
                }
            }
        }
        stage('Test'){
            steps{
                script {
                    sh 'cd jenkins-example && sum_test.py'
                }
            }
        }
    }

    post{
        failure{
            echo 'The pipeline failed.'
        }
    }
}