pipeline {
    agent none

    stages {
        stage('hello-world'){
            docker.image('python:3.10.1-alpine').inside {
                sh 'cd jenkins-example && python hello-world.py'
            }
        }
        stage('Test'){
            docker.image('python:3.10.1-alpine').inside {
                sh 'cd jenkins-example && python sum_test.py'
            }
        }
    }

    post{
        failure{
            echo 'The pipeline failed.'
        }
    }
}