---
version: '3'

services:

  # Reverse proxy using nginx
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
     - ping-pong
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

      
  # Main API
  ping-pong:
    image: ping-pong-api
    container_name: ping-pong-api
    build:
      context: ./ping-pong-api
    ports:
      - 3000:3000
    restart: on-failure 